### ISSUE TITLE
Parse `pyproject.toml` and `setup.cfg` files as well

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#107]
`setup.py` is being phased out generally in python projects favoring either `setup.cfg` to contain the metadata (and thus the dependencies), or even better `pyproject.toml`.

Currently `z3c.dependencychecker` refuses to work if no `setup.py` is found at all.

**Comment by jensens** [comment]
`setup.cfg` was used in past (intermediate), but in fact we should go for `pyproject.toml` and no `setup.*` at all, since this is the official standard.

**Comment by gforcada** [comment]
We need to support old packages though, rather than telling them to get updated with new standards before they can use this tool IMHO 😅
