### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#122]
What's listed on `CHANGES.rst` is good enough to make a new release IMHO.

I think I can do that, but just in case someone wants to cut it, please be my guests, otherwise in a few days I will do it myself 😄

**Comment by gforcada** [comment]
Done myself 😄 `2.12` is out! 🎉

**Comment by reinout** [comment]
Good that you did it yourself: I've been on holiday :-) Just got back.
