### ISSUE TITLE
Detect coverage dependency when using nose testrunner

### ISSUE THREAD

**Issue by reinout** [reinout/z3c.dependencychecker#14]
Perhaps this warrants a special case?
If the nose testrunner is used, a dependency on `coverage` is handy, but there's nothing in a project's code that imports it, so you get a warning.

Look at it.

Perhaps coverage is included in the latest nose versions? Making this problem irrelevant?

**Comment by gforcada** [comment]
With @mauritsvanrees idea on #41 to allow whitelistings, this should go away right?

**Comment by reinout** [comment]
Nose is old. I guess I'm the only one using both dependencychecker *and* the old nose. And we'll move to pytest. So I'm going to close this issue.
