### ISSUE TITLE
Dependency on FTIs are not detected

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#18]
I have a dexterity FTI like this:

```
...
   <element value="freitag.behavior.imageattachment.behaviors.IImageAttachment"/>
    <property name="klass">plone.dexterity.content.Container</property>
...
```

But z3c.dependencychecker thinks that ``plone.dexterity`` and ``freitag.behavior.imageattachment`` are not needed...

**Comment by reinout** [comment]
I'm out of plone development for too long to know what a "dexterity FTI" is.

In any case, I'm pretty sure that (whatever it is), it isn't checked by z3c.dependencychecker. By default it looks for regular python imports and a few special zope/plone cases like ZCML files. If a "dexterity FTI" is something new, some new code will have to be added.

**Comment by reinout** [comment]
For instance, look at https://github.com/reinout/z3c.dependencychecker/blob/master/src/z3c/dependencychecker/dependencychecker.py#L295 (the `includes_from_zcml()` function). Quite simple and short. The regular expression it uses is verbose, so it should be reasonably readable.

You'd need to duplicate this function for dexterity. (Just like there's a special function for finding additional needed imports from django settings files, for instance).

Note that I haven't personally done anything with the code in the last year or so, so before you can start working on it (to get the tests running) you might have to update the bootstrap script and buildout versions and so.

**Comment by gforcada** [comment]
A Dexterity FTI is this: https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/profiles/default/types/Document.xml

Thanks for the tips I was already thinking of implementing it myself (given enough time...), having quick responses from you are motivating enough to make the pull request at least :-)

**Comment by reinout** [comment]
If you have any further questions, feel free to ask here :-) It might even mean I'm going to do some work on z3c.dependencychecker myself:  the django integration is incomplete, still.

**Comment by reinout** [comment]
Thanks for the buildout/setup/travis fixes! I guess this means you can solve the dexterity FTI yourself?

**Comment by gforcada** [comment]
Sorry for the PR noise!

And yes, I hope to send you a pull request in some hours/days.

**Comment by reinout** [comment]
@mauritsvanrees: you're one of the plone releasers now, right? Once this issue is fixed, using z3c.dependencychecker to clean up the `install_requires` list of the various plone packages might be a very very good idea! It was used to clean up the zope dependencies 6 years ago, perhaps plone can also profit from some explicitness.

**Comment by reinout** [comment]
@gforcada: no problem with the PR noise :-) You're fixing/cleaning things and that's always good. I don't mind a bit of noice. Noice like this is like music to my ears: someone else is doing work I'd otherwise have to do :-)

**Comment by gforcada** [comment]
Already fixed
