### ISSUE TITLE
Marks as unneeded a zope package

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#23]
Having ``zope.schema`` on ``setup.py`` and using it like this:

``from zope import schema``

makes ``z3c.dependencychecker`` think that ``zope.schema`` is not needed as ``Zope`` is already a package? My current guess.

Not sure how to handle this nor where to start looking for.

**Comment by jone** [comment]
Is `runpy` available at the python you are using? Can you `import runpy`?

Actually it should work like this (when `runpy` is available):
The runpy-loader is asked for the file path of a dottedname, e.g.:
```python
>>> import runpy
>>> loader = runpy.get_loader('zope.schema')
>>> loader.get_filename()
'/Users/jone/projects/python/cache/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/__init__.py'
```
Then the `PKG-INFO`-file is searched (is located in an egg-info directory of any parent directory of this path).
In the `PKG-INFO` file there is a line with the package name:
```
Name: zope.schema
```

When runpy is not available, the dottedname is used without further lookup / conversion.

--

But I have also a strange behavior I cannot currently explain:
I have a `zope.schema` import in the code and a `zope.schema` dependency in the `setup.py` but the dependencychecker still lists it in `Missing requirements`, although I have declared the dependency.

**Comment by gforcada** [comment]
I will check, thanks for the tip

**Comment by gforcada** [comment]
Yes I do have ``runpy`` available.

For me it currently tells me that that is an unneeded dependency...

**Comment by reinout** [comment]
Can you run dependencychecker with the `-v` option and post the results? Perhaps that'll help in figure out what goes wrong.

**Comment by gforcada** [comment]
I will do and report back.

**Comment by gforcada** [comment]
Aha! I think I have a better idea, still need to look at the code though...

The imports look like this:
```
from z3c.form import form
from z3c.form import interfaces
from zope import interface
from zope import schema
```

And the debug information reports it as:

```
DEBUG: Modules found in /home/gil/foo.py (test-only: False):
    ['z3c.form.form', 'zope.interface']
```

So as they share the same root (zope) it just ignores any further import from the same root (just like with z3c.form).

If I reverse the order (first zope.schema then zope.interface) it shows the opposite as expected.

I will try to cook a PR for it.

**Comment by reinout** [comment]
Maybe #16 is related?

**Comment by gforcada** [comment]
I think I found the problem, still thinking on the solution... This line https://github.com/reinout/z3c.dependencychecker/blob/master/z3c/dependencychecker/importchecker.py#L99 and the function itself kind of expects that **all** imports from a module will be done within a single line, i.e:
```
from zope.interface import alsoProdives, directlyProvides, something_else
```

If instead you have it like this:
```
from zope.interface import alsoProdives, directlyProvides
from zope.interface import something_else
```

Only the first line is actually saved, the ``setdefault`` prevents anything else to be added later.

The solution I guess is to move that to a list, but then I guess quite a refactoring needs to be done throughout that module. I'm looking at it. But suggestions welcome.

**Comment by reinout** [comment]
I released 1.13. Can you check if that one works for you?

**Comment by reinout** [comment]
@gforcada: I just gave you write access to the repository, that probably makes it easier to work with branches. It also means you can close issues if you want.

Thanks for the work you've done. You've gotten me involved again, too :-)

**Comment by gforcada** [comment]
Thanks a lot, yes it will be a bit easier for the branches at least :)
