### ISSUE TITLE
Make sure it runs on python 3

### ISSUE THREAD

**Issue by reinout** [reinout/z3c.dependencychecker#32]
TODO: print statements adjustments and so.

**Comment by gforcada** [comment]
There's a bigger elephant on the room: ``importchecker.py`` is using the ``compiler`` module that got removed on python 3, I guess that maybe we need to move that code to use the ``ast`` one?

**Comment by reinout** [comment]
Ouch, looks that way, yes. I personally haven't used ast (or the compiler module) a lot. Most of the importchecker.py code is directly copied from a zope helper function somewhere.

**Comment by gforcada** [comment]
Should we keep making releases on the 1.x series with a command line switch to use either of the implementations and remove the old one for a 2.0 release with python 3 support? 🤔

**Comment by reinout** [comment]
Just remove the old implementation. If someone needs the old version, they can just use an old release.

Just making sure: the new implementation is for both python 2.7 and 3.x?

**Comment by gforcada** [comment]
@reinout ok, I will remove them, I wanted to keep a command line switch for a while so we can easily compare the output of the two implementations out in the wild (i.e. get all 300 Plone packages, run dependencychecker on all of them with the two implementations, store that ouput and compare the two versions).

I'm sure that there will be plenty of corner cases.

And yes, the new implementation is working fine for 2.7 and last time I checked there was only 1 single test that was failing on 3.6, a really minor one though.

**Comment by reinout** [comment]
Well, I assumed it would be quickest/easiest to just remove the old implementation.
If it is easy to keep it around for debug purposes, that's fine with me, too.

**Comment by reinout** [comment]
2.0 runs on python 3!
