### ISSUE TITLE
Ignore relative imports

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#37]
I just noticed that one module was doing a relative import `.behavior import IMyBehavior` and z3c.dependencychecker was reporting that I was missing the behavior.IMyBehavior distribution on setup.py.

Shouldn't those be ignored? Just like we do on the ZCML declarations with the `if not module.startswith('.')`?

**Comment by reinout** [comment]
Yes, sounds like a good one.

**Comment by gforcada** [comment]
On the new implementation this is already the case, as I guess the current/old implementation is not going to be developed further, should we close this one and marked as fixed in version 2.0 (which could be the point where we switch to the new implementation)?

**Comment by reinout** [comment]
That's ok. So: "fixed in the upcoming 2.0" :-)
