### ISSUE TITLE
Check dependencies of arbitrary distributions

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#40]
Use case: I would like to add a part on buildout.coredev to install ``z3c.dependencychecker`` like:

```
[deps]
recipe = zc.recipe.egg
eggs =
    ${instance:eggs}
    z3c.dependencychecker
```

And then being able to check undeclared dependencies on any distribution found in src, i.e.

```
for dist in src/*:
    ./bin/deps $dist
done
```

So far seems it is really not possible. Would it be desirable to do so?

**Comment by reinout** [comment]
In principle, yes. Is there a specific problem you're seeing? Or is it a matter of allowing different commandline parameters or so?

**Comment by gforcada** [comment]
The problem I had is that I have two distributions with their own ``bin/dependencychecker``.

If I run them without any parameter both run fine and report the right information, but if I try to run ``bin/dependencychecker`` of one distribution on another one (i.e. ``bin/dependencychecker ../collective.contentalerts``) I wrong output.

I got the impression that as you can pass a path to ``bin/dependencychecker`` you can point to a distribution top-level folder and the setup.py and its .egg-dir info will be used.

**Comment by reinout** [comment]
I recently also did some more testing and I found out that dependencychecker needs to have the various eggs available. It uses `pkg_resources` to find packages in order to match imports to package names, for instance. So pkg_resources needs to be able to find those packages. And packages installed in another buildout aren't findable (unless we work around that).

So: is it possible in your setup to get a `bin/dependencychecker` somewhere that has all the necessary eggs?

**Comment by gforcada** [comment]
(sorry that took longer than expected :S)

Doing it like I wanted throws an error:

```
./bin/dependencychecker src/Products.CMFCore
can't open file 'setup.py': [Errno 2] No such file or directory.egg-info/requires.txt found, exiting
```

The workaround is doing:

```
cd src/Products.CMFCore
../../bin/dependencychecker
```

So as long as dependencychecker has access to all eggs you can run it on any folder, but you can not run it from a single standalone location to any arbitrary path.

**Comment by gforcada** [comment]
So actually the workaround is not that bad after all...
