### ISSUE TITLE
Allow configuring dependencychecker, especially meta dependencies

### ISSUE THREAD

**Issue by mauritsvanrees** [reinout/z3c.dependencychecker#41]
What I mean is: in Plone packages you often do not import `Zope2`, but you import for example `Products.Five`.  But `Products.Five` is included in the `Zope2` package, at least for versions currently in use by Plone.

Let me give an example. For `collective.searchandreplace` I have updated the `setup.py` using dependency checker.  See https://github.com/collective/collective.searchandreplace/blob/663b9c5f7d44ce2f022bed18f4decd02f0a8ba4f/setup.py

Result:

```
Missing requirements
====================
     Products.Five.browser.pagetemplatefile.ViewPageTemplateFile

Missing test requirements
=========================
     Products.Five.fiveconfigure
     Products.Five.testbrowser.Browser
     Testing.ZopeTestCase
     Testing.ZopeTestCase.FunctionalDocFileSuite

Unneeded requirements
=====================
     Products.CMFPlone
     Zope2

```

Those missing requirements are already included in Zope2.  It would be nice if there was a way to tell this to dependencychecker.

Also, `Products.CMFPlone` is not itself imported, but I have added it because the package only makes sense in the context of a Plone site.

So I wonder if there is already something that handles this, or if the code can be improved to somehow realise that those packages are really part of a different package.

Otherwise I wonder if a config file can help.  Say a `~/.dependencychecker.cfg`:

```
[dependencychecker]
# Do not complain about these unneeded requirements:
unneeded_whitelist = Products.CMFPlone
# Maybe also:
# missing_whitelist = ...
# unneeded_test_whitelist = ...
# missing_test_whitelist = ...

[provides]
# Packages that provide (contain) other packages:
Zope2 =
    Products.Five
    Testing
```

**Comment by reinout** [comment]
I like the "provides" solution! That does exactly what's needed.

Would it make sense to put a `[dependencychecker_provides]` section in the `setup.cfg`?

**Comment by mauritsvanrees** [comment]
That makes sense. We can look for it there and in pypirc, just like zest.releaser does.

**Comment by idgserpro** [comment]
Some progress here?

**Comment by idgserpro** [comment]
Maybe you should have a metapackages configuration, instead of having the provides. In case of Zope2 any folder inside the egg should be considered a package and be ignored by dependencychecker.

The configuration would look something like:

```
[dependencychecker]
# Do not complain about these unneeded requirements:
unneeded_whitelist = Products.CMFPlone
# Maybe also:
# missing_whitelist = ...
# unneeded_test_whitelist = ...
# missing_test_whitelist = ...

metapackages =
    Zope2
```

It would be more automatic.

**Comment by reinout** [comment]
Maurits, did you intend to do a pull request for this?

**Comment by mauritsvanrees** [comment]
I might.

metapackages: nice idea, thanks, but I think that could lead to too many false positives. Zope2 itself has a Products directory, which would probably result in dependencychecker not warning anymore about missing for example a Products.statusmessages dependency. And if we somehow blacklist Products from the metapackages, then the user would need to specify the included Products.Five and Products.PageTemplates after all.
So I think there is some gain and some pain...

**Comment by idgserpro** [comment]
@mauritsvanrees but it would have to be checked. In ```Zope2``` there is not ```Products/statusmessages``` folder. So will I be warning if someone tries to import ```Products.statusmessages```.

**Comment by mauritsvanrees** [comment]
Thinking about this, to check this, the dependencychecker would need to look in the Zope2 package, so it would need the Zope2 package on its path, plus all other Plone dependencies and/or Django dependencies if you want to use it on Django projects as well, and possibly various versions.  Or it would need to `pip install` packages in the background while doing its checks... I don't see this happening. Too much complexity.
I am much more in favour of letting the user specify this explicitly in a config file.

**Comment by gforcada** [comment]
@mauritsvanrees I thought that to run properly dependencychecker you needed to put all your eggs on it (using it together with buildout)

**Comment by mauritsvanrees** [comment]
Nope:

```
$ cat $(which dependencychecker )
#!/usr/local/pythons/python-2.7/bin/python2.7

import sys
sys.path[0:0] = [
  '/Users/maurits/shared-eggs/z3c.dependencychecker-1.15-py2.7.egg',
  '/Users/maurits/shared-eggs/setuptools-19.3-py2.7.egg',
  ]

import z3c.dependencychecker.dependencychecker

if __name__ == '__main__':
    sys.exit(z3c.dependencychecker.dependencychecker.main())
```

So only two packages are in the script.

For the package that you want to run this on, you do have to run buildout or `python setup.py egg_info` to get the current dependency information according to `setup.py`. The script says:

> Note: requirements are taken from the egginfo dir, so you need
> to re-run buildout (or setup.py or whatever) for changes in
> setup.py to have effect.

**Comment by idgserpro** [comment]
@mauritsvanrees  is right. The dependencychecker doen't know where the packages are. To work we would have to indicate to it. Something like:

```
[metapackages]
Zope2=/path/to/Zope2-2.13.24-py2.7.egg
```
I do not know if that's a good idea.

**Comment by mauritsvanrees** [comment]
I have just added pull request #43 with a minor cleanup.

Based on that branch, I have started a branch with a `setup.cfg` reader. The reader is there, but it is not used yet. Work in progress (feel free to take over).
See https://github.com/mauritsvanrees/z3c.dependencychecker/tree/maurits-setup-cfg

**Comment by idgserpro** [comment]
@mauritsvanrees would not it be the case to move these products out of ```Zope2```?

**Comment by mauritsvanrees** [comment]
@idgserpro Sometimes a product gets moved out of Zope2. But most remain within Zope2 because they make no sense on their own.

**Comment by gforcada** [comment]
@mauritsvanrees while working on #54 I noticed that this would be indeed needed. I thought that rather than on setup.cfg maybe it make more sense to your pyproject.toml and slowly move *everything* there? Are you planning to work on this still?

**Comment by mauritsvanrees** [comment]
I have not used `pyproject.toml` yet. I see it is about build requirements. For most Plone packages, you don't need Plone or Zope2 to build the package: you usually only need setuptools. So this seems different.

I have no immediate plans to work on this. It *would* be useful for Plone, especially for detecting that some packages may not be needed anymore so we don't need to port them to Python 3. Or to detect that a package is still depending on Archetypes. So I might end up working on it. Not this year. ;-)

**Comment by reinout** [comment]
`pyproject.toml` is a bit on the new side. I'm not using it myself yet :-) It *is* one of the things I'll look at in january.

So unless there's a very good reason, I'd put it in setup.cfg for now.

(I assume that both setup.cf and pyproject.toml will live side by side for quite a long while, so we might need to support them both).

**Comment by gforcada** [comment]
My idea with pyproject.toml is that it is meant to be used not only for building the package (as per [PEP 518](https://www.python.org/dev/peps/pep-0518/)), but as already stated there, use the ``[tools.z3c.dependencychecker]`` sub-table to store the these meta dependencies.

See the [two paragraphs above this header](https://www.python.org/dev/peps/pep-0518/#rejected-ideas).

I expect that developers will start to use pyproject.toml more and more as python and its ecosystem pushes more bits in it.

And as it is a TOML file it should be easier to parse and use, so rather than setup.cfg I would prefer that one. There is some rationale on that PEP about why TOML as well.

**Comment by gforcada** [comment]
I think we can close this one already.... reopen if not.

**Comment by reinout** [comment]
Yes, closing it is fine.
