### ISSUE TITLE
rewrite tests?

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#47]
The more I'm looking at the code, or rather how to refactor and rewrite it from scratch (picking up what's still interesting), the more I want to look at the tests...

Which leads me to a situation where I would actually like to rewrite them to be regular unittest tests, which would mean that we could use something like pytest or the likes to run, rather than ancient and barely developed z3c.testsetup and zope.testing.

@reinout @mauritsvanrees What do you think?

**Comment by reinout** [comment]
Getting rid of z3c.testsetup and so: 100% fine :-)

**Comment by gforcada** [comment]
Done on #50
