### ISSUE TITLE
Can we get any inspiration from pipreqs?

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#57]
See https://github.com/bndr/pipreqs

The idea of using a mapping, see https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping is interesting, specially for all those Packages built into Zope2 and ZODB meta-distributions.

**Comment by reinout** [comment]
Looks interesting.
I'm getting quite a number of unrecognized imports/packages (appconf/django-appconf, oidc_provide/django-oidc-provider). One is in that pipreqs list, but three are missing.

The old version, if I remember correctly, attempted to do an import. That's quite brute-force and possibly error-prone (read: circular imports). For many cases, it worked, though.

Perhaps we can ask pkg_resources for metadata on importable stuff?

**Comment by gforcada** [comment]
I would say that we can close this already, reopen if you think otherwise 😄
