### ISSUE TITLE
Speed improvement

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#65]
z3c.dependencychecker is not slow per se,  but both implementations have a shared problem:  they keep scanning the filesystem for files with possible imports.

On the new implementation for example that happens for every single class in modules.py.

I see two different approaches on optimizing this:

- use VCS information (we should add another warning about it then)
- use MANIFEST.in information (again a new warning would be useful)

The big downside would be testing, either approach would make tests a bit more complex, though with a pytest fixture the solution can be elegant enough to not be too cumbersome.

Ideas? Should that be a real concern? 🤔

**Comment by reinout** [comment]
Ideally, this isn't much of a problem. The code is *normally* in a subdirectory underneath `setup.py`. The `var/media/bunch_of_css_and_js` stuff is elsewhere on the filesystem.

Isn't it so that we try to detect that directory? And alternatively, you can pass it on the commandline? 
That should be enough in the majority of cases, I think.

**Comment by gforcada** [comment]
Well, I do have at least a package that inside it I have a node_modules with thousands of files and folders in it (side note: that's why I wrote [yarn.build](https://pypi.org/project/yarn.build) )

**Comment by reinout** [comment]
Suggestion: add a `--ignore` option to filter out a specific directory (including `setup.cfg` setting, if practical). That is probably less work and less error-prone than parsing git/hg/bzr/svn and/or MANIFEST.in

**Comment by gforcada** [comment]
I already hit a problem with this 😖 a new JS dependency installed `typescript` and inside `node_modules/typescript` there is a [`ThirdPartyNoticeText.txt`](https://github.com/microsoft/TypeScript/blob/main/ThirdPartyNoticeText.txt) that is parsed by the `DocFiles` class in `z3c.dependencychecker.modules` and it gets a `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 6038: invalid start byte`

**Comment by reinout** [comment]
Nowadays, `.gitignore` support should get us most of the way there, so looking at an ignore file is more doable.

But.... `node_modules/` is a pretty standard location, too. And there's normally never python code in there. Can we get by with a quick hardcoded exclude of `node_modules/`? What do you think?
