### ISSUE TITLE
Scan tox.ini files?

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#66]
While testing the new implementation I cam across [plone.memoize](https://github.com/plone/plone.memoize).

The new implementation complains that zope.testrunner is a testing dependency that is not needed, but looking at the repository, one notices that is installed with tox.ini on the ``deps = `` variable.

Comments?

**Comment by reinout** [comment]
@mauritsvanrees, you can say more about this.

I'd say that it is OK to omit tox.ini. Effectively 'testrunner' is something that is run from the commandline. It could just as well be a line in a `Jenkinsfile` or an instruction in a `README.rst`. 

Weird in a way that the testrunner isn't imported in some test.

**Comment by mauritsvanrees** [comment]
I would say that `zope.testrunner` should not be a test dependency: the tests themselves do not need it. You need a way to run the tests, and `zope.testrunner` can do that, but I guess there are other ways to run the tests.

I see various packages that have `zope.testrunner` as test dependency, but most of them actually import from `zope.testrunner` in their `setup.py`. See for example [zope.annnotation](https://github.com/zopefoundation/zope.annotation/blob/4.4.1/setup.py#L32). For that package it is gone on master. Well, the import is gone, but the dependency is still there. Hardly any Plone packages specify this as dependency.

We *could* look at `tox.ini` and not complain about a test dependency when it is installed there, but then you would need a separate `tox.ini` dependency checker: maybe stuff gets installed in tox that is no longer needed.

It may be better if this is put in a (future) whitelist in the `setup.cfg` of this package.

**Comment by gforcada** [comment]
Right, then let's close this then.
