### ISSUE TITLE
Empty pypi page

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#71]
@reinout as you can log in on pypi, I see that both the current and the new pypi pages for z3c.dependencychecker are completely empty... 😞 

Somehow the description and long_description from setup.py could not be extracted... I don't see why though... any idea?

**Comment by reinout** [comment]
Weird.... The long_description is fine. I've tested the syntax locally and everything's OK.
Might be a pypi glitch.
