### ISSUE TITLE
quiet or error code?

### ISSUE THREAD

**Issue by gforcada** [reinout/z3c.dependencychecker#82]
My ultimate goal with z3c.dependencychecker has been to be able to untangle the dependency mess in Plone. Now that we are reaching the critical point with #81 there is only one thing missing: how to make z3c.dependencychecker CI friendly.

Right now we don't set an exit code if there are problems with the dependencies nor we have a completely empty output (that could be signaling it) as we are printing the notice about re-running setup.py to update the egg_info.

I have a branch that adds a new command line parameter ``-q --quiet`` that simply does not show the notice, and thus CI could use that.

But before pushing that, should we do this parameter or the status code? Both? Opinions?! :thinking:

**Comment by reinout** [comment]
A status code is more explicit. I guess the "--quiet" can lead to some hard decisions about log levels.

I took a look at flake8: apparently they do return an exit code by default. There's even an option to quiet that down:

    --exit-zero           Exit with status code "0" even if there are errors.

Might be a good idea to add that. I can imagine people wanting to run dependencychecker only for the output.

Unrelated: **wow**, I never imagined that dependencychecker could be run as a regular CI checker. I was so used to interpreting it manually. You really did a good job!

**Comment by gforcada** [comment]
Ok, so rather than a ``--quiet`` we do a ``--exit-zero`` and by default we show the exit status as 1 if there is anything to report. I will try to get that tonight.

**Comment by gforcada** [comment]
That was released in 2.4
